[package]
name = "jblisp2"
version = "0.0.1"
authors = ["Jérome Boisvert-Chouinard"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
regex = "1"
rustyline = "8.2"
lazy_static = "1.4"
