[package]
name = "jbscheme"
version = "0.0.3"
authors = ["Jérome Boisvert-Chouinard"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
lazy_static = "1.4"
regex = "1"
rustyline = "8.2"
structopt = "0.3"
