site_name: JB Scheme
site_url: https://jbchouinard.github.io/jbscheme
theme: readthedocs
nav:
  - Lanuage Reference: index.md
  - Dowload PDF: /jbscheme/JB Scheme Manual.pdf
  - Crate Documentation: /jbscheme/crate/jbscheme/index.html
  - GitHub Repo: https://github.com/jbchouinard/jbscheme

