site_name: Jibi Scheme
site_url: https://jbchouinard.github.io/jibi
theme: readthedocs
nav:
  - Language Reference: index.md
  - Dowload PDF: /jibi/Jibi Scheme Manual.pdf
  - Crate Documentation: /jibi/crate/jibi/index.html
  - GitHub Repo: https://github.com/jbchouinard/jibi

